### ISSUE TITLE
[調査]Netlify CMSについて

### ISSUE THREAD

**Issue by smatsuda0620** [covid19jc/web#1]
[観点]
- 現環境でのNetlify CMS導入方法(InfoをCMSで追加、編集したい)
- リッチテキストで記入できるか
- Indentifyで複数アカウントの認証できるか
- Preview機能があるか、ある場合どの程度まで再現できるか

**Comment by nacl30d** [comment]
調査結果を[Netlify CMS調査](../wiki/Netlify-CMS調査)にまとめました

**Comment by smatsuda0620** [comment]
@d-salt ありがとうございます！確認させていただきます。

**Comment by smatsuda0620** [comment]
@d-salt ありがとうございます。おかげで導入できました。
