### ISSUE TITLE
献金の方法の新サイトへの掲載

### ISSUE THREAD

**Issue by smatsuda0620** [covid19jc/web#5]
オンライン礼拝と同様に情報を新サイトへ転機する。
https://docs.google.com/presentation/d/1rIUKc0u-SK1iVEKDrtbucDvINS121qDQ02NcYkaYwQo/edit#slide=id.g82de86d373_111_16

cmsでも変更できるようにadminのcollectionへも追加する。

**Comment by smatsuda0620** [comment]
@d-salt お手数ですが、こちらお願いしてもよろしいでしょうか。

**Comment by nacl30d** [comment]
@smatsuda0620 引き受けました．
